/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "cf58cba358d31ce285c1970a79a9411d0fb381a5"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
