/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "dda581d538cb6532cda841444e7b4ceacde01ec9"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
